title: "GMO-check Pipeline report"
subtitle: "Best-practice workflow for detecting GMOs from short read data"
custom_logo: "pipelinelogo.png"
custom_logo_title: "marchoeppner/gmo-check"
custom_logo_url: "http://www.github.com/marchoeppner/gmo-check"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass
    - _noMatch

report_comment: >
    This report has been generated automatically by marchoeppner/gmo-check.
    For help interpreting the outputs, please see: https://github.com/marchoeppner/gmo-check
report_header_info:
    - Contact E-mail: "marc.hoeppner@lsh.landsh.de"
    - Application Type: "Variant detection"

top_modules:
    - 'general_stats'
    - 'gmo_check_result'

report_section_order:
    software_versions:
        order: -1001